doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
<<<<<<< HEAD
=======
    storage:
        table_storage:
            table_name: doctrine_migration_versions
            version_column_name: version
            version_column_length: 191
            executed_at_column_name: executed_at
            execution_time_column_name: execution_time
>>>>>>> a3faf68b6604ba7c00e7a1f70865a40a96aacf2d
    enable_profiler: false
