# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    gemini_api_key: '%env(GEMINI_API_KEY)%'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    # On configure l'argument du service spécifiquement
    App\Service\AiCoachService:
        arguments:
            $apiKey: '%env(GEMINI_API_KEY)%' # On pioche directement dans le .env

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones